env = Environment()
    
env.ParseConfig("pkg-config --cflags --libs " +
                "clanCore-1.0 " +
                "clanApp-1.0 " +
                "clanDisplay-1.0 " +
                "clanSDL-1.0 " +
                "clanSound-1.0 " +
                "| sed 's/-I/-isystem/'")

env.SharedLibrary(
    target = "advent",
    source = [
    "adv_hook.cxx",
    "adv_hook_smob.cxx",
    "adv_obj.cxx",
    "advent_main.cxx",
    "button_layer.cxx",
    "coin_layer.cxx",
    "collideable.cxx",
    "collideable_smob.cxx",
    "colmap.cxx",
    "colmap_smob.cxx",
    "debug.cxx",
    "delayed_adv_hook.cxx",
    "display.cxx",
    "display_view.cxx",
    "drawable.cxx",
    "drawable_adv_obj.cxx",
    "drawable_display.cxx",
    "drawable_layer.cxx",
    "drawable_smob.cxx",
    "empty_adv_obj.cxx",
    "fade_out_layer.cxx",
    "font_sprite.cxx",
    "guile.cxx",
    "inactive_layer.cxx",
    "instant_adv_hook.cxx",
    "inventory.cxx",
    "key_map.cxx",
    "key_map_handler.cxx",
    "layer.cxx",
    "layer_group.cxx",
    "layer_screen.cxx",
    "layer_smob.cxx",
    "mouse_cursor.cxx",
    "person.cxx",
    "person_gfx.cxx",
    "polygon_collideable.cxx",
    "rect_collideable.cxx",
    "rect_sprite.cxx",
    "resource_manager.cxx",
    "scenario.cxx",
    "scenario_layer.cxx",
    "screen_manager.cxx",
    "sprite.cxx",
    "sprite_collideable.cxx",
    "sprite_drawable.cxx",
    "sprite_group.cxx",
    "sprite_smob.cxx",
    "surface_colmap.cxx",
    "surface_sprite.cxx",
    "time_manager.cxx",
    "view.cxx"
    ])

# EOF #
