#!/usr/bin/guile-1.8 \
-e main -s
!#

;; Retriever doesn't seem to be in working order

(set! %load-path (cons (string-append (getcwd)) %load-path))
(chdir "doc/examples/retriever/")
(load "retriever.scm")

;; EOF ;;
